### ISSUE TITLE
accessories not showing in home?

### ISSUE THREAD

**Issue by paqpaqpaq** [ncovercash/homebridge-zway-schlage-be469#7]
Hi,

I just installed your plugin, all fine, log shows found items, but nothing is showing in the home app.
Ignore list is empty.

Any ideas?

**Comment by ncovercash** [comment]
Wow, I was never honestly expecting anyone else to use this plugin!  Do they show on the config site's accessories tab?

**Comment by paqpaqpaq** [comment]
heheheh ;)

I didn't run Homebridge -I, but I tried, and it doesn't show up there either.

Well, it is there, but via a different plug-in.
This is the log:

[2020-6-2 16:53:49] [schlage-be469] Finished launching
[2020-6-2 16:53:49] [schlage-be469] Sending initial request to enumerate devices...
[2020-6-2 16:53:49] [schlage-be469] No requests have been made so far, looking for a session.
[2020-6-2 16:53:49] [schlage-be469] Got session 466aab...
[2020-6-2 16:53:49] [schlage-be469] Testing access
[2020-6-2 16:53:49] [schlage-be469] Success, session is valid!  Good to go!
[2020-6-2 16:53:49] [schlage-be469] Your controller appears to be a Z-Wave.Me!
[2020-6-2 16:53:49] [schlage-be469] Found #1:  ( Static PC Controller)
[2020-6-2 16:53:49] [schlage-be469] Found #7:  Danalock V3 (Poly-control Secure Keypad)

I also see a connection on the z-way-server end.

**Comment by ncovercash** [comment]
Ah, this plugin is hardcoded to support specifically the BE469 lock, and this lock alone.  However, if you would like to see if this works with your own device by adding a clause to [this if statement](https://github.com/ncovercash/homebridge-zway-schlage-be469/blob/master/src/index.ts#L312).  When the plugin registers a device that it supports it will log `Identified this as a lock to be served by this platform`.  If you're unable to figure out how to test it yourself, I can try making a branch for you to test it with)

**Comment by paqpaqpaq** [comment]
Ah OK I understand.
No problem, I will fix something.

**Comment by ncovercash** [comment]
I'd love to add support for the lock, I just need more information about it!  If you could share with me the model information I'd be happy to work on adding it!

**Comment by paqpaqpaq** [comment]
It's the Danalock V3 Z-wave

**Comment by ncovercash** [comment]
Cool, I found configuration parameters/documentation for it.  Will work on implementing.

**Comment by paqpaqpaq** [comment]
Thanks.  Just FYI, I did get it working with an old plugin, and actually works fine. So please do;nt do all of this just for me :)

**Comment by ncovercash** [comment]
What plugin, if ya don't mind me asking?

**Comment by paqpaqpaq** [comment]
https://www.npmjs.com/package/homebridge-zway

**Comment by ncovercash** [comment]
Hm, I was never able to get that to work with my locks.  Thanks for trying my package though, I'm still amazed someone actually found it!
